const MENU_ITEMS = [
  {
    id: '1',
    name: 'Burger',
    calories: 520,
    sugar: 9,
    sodium: 980,
    fat: 31,
    ingredients: ['beef', 'bun', 'cheese'],
    fried: true,
  },
  {
    id: '2',
    name: 'Pizza',
    calories: 420,
    sugar: 6,
    sodium: 760,
    fat: 18,
    ingredients: ['wheat', 'cheese', 'tomato'],
    fried: false,
  },
  {
    id: '3',
    name: 'Fries',
    calories: 360,
    sugar: 1,
    sodium: 640,
    fat: 17,
    ingredients: ['potato', 'salt', 'oil'],
    fried: true,
  },
  {
    id: '4',
    name: 'Soft Drink',
    calories: 210,
    sugar: 42,
    sodium: 65,
    fat: 0,
    ingredients: ['water', 'sugar', 'flavor'],
    fried: false,
  },
  {
    id: '5',
    name: 'Salad',
    calories: 180,
    sugar: 4,
    sodium: 220,
    fat: 8,
    ingredients: ['lettuce', 'tomato', 'cucumber'],
    fried: false,
  },
];

module.exports = MENU_ITEMS;
